spring.application.name=finance-transaction-service

spring.datasource.url=jdbc:postgresql://localhost:5432/finance_transactions
spring.datasource.username=finance_user
spring.datasource.password=finance_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

server.port=8081